package com.ruoyi.iotlighting.domain.protocol;

import com.ruoyi.common.utils.DataUtils;
import com.ruoyi.iotlighting.domain.TerInfo;

import java.util.List;  // ← FIXED: this was missing

public class LightingConfig extends ProtocolData {

    private int lightingCount;
    private List<TerInfo> terInfoList;

    public int getLightingCount() {
        return this.lightingCount;
    }

    public void setLightingCount(int lightingCount) {
        this.lightingCount = lightingCount;
    }

    public List<TerInfo> getTerInfoList() {
        return this.terInfoList;
    }

    public void setTerInfoList(List<TerInfo> terInfoList) {
        this.terInfoList = terInfoList;
    }

    // equals, hashCode, toString generated by decompiler (you can replace with Lombok @EqualsAndHashCode / @ToString if desired)
    @Override
    public boolean equals(Object o) {
        if (o == this) return true;
        if (!(o instanceof LightingConfig)) return false;
        LightingConfig other = (LightingConfig) o;
        if (!other.canEqual(this)) return false;
        if (getLightingCount() != other.getLightingCount()) return false;
        List<TerInfo> thisTerInfoList = getTerInfoList();
        List<TerInfo> otherTerInfoList = other.getTerInfoList();
        return (thisTerInfoList == null) ? (otherTerInfoList == null) : thisTerInfoList.equals(otherTerInfoList);
    }

    protected boolean canEqual(Object other) {
        return other instanceof LightingConfig;
    }

    @Override
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + getLightingCount();
        List<TerInfo> $terInfoList = getTerInfoList();
        result = result * PRIME + (($terInfoList == null) ? 43 : $terInfoList.hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "LightingConfig(lightingCount=" + getLightingCount() + ", terInfoList=" + getTerInfoList() + ")";
    }

    public String getHexData() {
        StringBuffer sb = new StringBuffer();
        sb.append(DataUtils.string2HexString(getStart()));
        sb.append(DataUtils.intTohex(getVersion()));
        sb.append(DataUtils.intTohex(getOption()));

        if (getLightingCount() <= 255) {
            sb.append(DataUtils.intTohex(0));
        }
        sb.append(DataUtils.intTohex(getLightingCount()));

        for (TerInfo terInfo : this.terInfoList) {
            sb.append(DataUtils.string2HexString(terInfo.getSn()));
            sb.append(DataUtils.intTohex(1));
            sb.append(DataUtils.intTohex(1));
            sb.append(DataUtils.intTohex(terInfo.getPointX().intValue()));
            sb.append(DataUtils.intTohex(terInfo.getPointY().intValue()));
        }

        sb.append(DataUtils.string2HexString(getEnd()));
        return sb.toString();
    }
}